services:
  llmdash:
    image: ${DESKTOP_PLUGIN_IMAGE}
    volumes:
      - llmdash-config:/llmdash
      - shared-grafana-files:/grafana
      - shared-prometheus-files:/prometheus
    ports:
      - 4444:4444

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 4445:4445
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      # Create a named volume for the prometheus data
      - prometheusdata:/prometheus
      # Share the named volume with the prometheus container
      - shared-prometheus-files:/etc/prometheus
    depends_on:
      - llmdash

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 2999:3000
    volumes:
      # Share the named volume with the grafana container
      - shared-grafana-files:/etc/grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    depends_on:
      - prometheus