# ================== Backend Builder ==================
FROM golang:1.21-alpine AS backend-builder
ENV CGO_ENABLED=0
RUN apk add --update make
WORKDIR /backend

RUN --mount=target=. \
    --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod download

RUN --mount=target=. \
    --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    OUT=/service make bin

# ================== Configure Extension ==================
FROM docker:cli
LABEL org.opencontainers.image.title="LLMDash" \
    org.opencontainers.image.description="Caching extension for LLMs" \
    org.opencontainers.image.vendor="Metaprov" \
    com.docker.desktop.extension.api.version=">= 0.2.3" \
    com.docker.extension.screenshots="" \
    com.docker.extension.detailed-description="" \
    com.docker.extension.publisher-url="" \
    com.docker.extension.additional-urls="" \
    com.docker.extension.changelog=""

COPY docker-compose.yaml .
COPY docker-compose.llmdash.yaml .
COPY metadata.json .
COPY llmdash.svg .

COPY --from=backend-builder /service /

# Copy grafana and prometheus configurations into extension image
COPY configs/grafana grafana
COPY configs/prometheus prometheus

# ================== Start Extension Backend ==================
CMD /service -socket /run/guest-services/backend.sock
