name: llmdash
services:
  llmdash:
    image: docker.io/metaprov/llmdash:latest
    environment:
      - LLMDASH_FLASH_DIR=/llmdash
      - BIND_ADDR=0.0.0.0:6060
    ports:
      - 6060:6060
    volumes:
      - llmdash-data:/llmdash

volumes:
  llmdash-data: