services:
  llmdash:
    image: ${DESKTOP_PLUGIN_IMAGE}
    volumes:
      - /var/run/docker.sock.raw:/var/run/docker.sock
      - shared-grafana-files:/grafana
      - shared-prometheus-files:/prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9080:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      # Create a named volume for the prometheus data
      - prometheusdata:/prometheus
      # Share the named volume with the prometheus container
      - shared-prometheus-files:/etc/prometheus
    depends_on:
      - llmdash

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 2999:3000
    volumes:
      # Share the named volume with the grafana container
      - shared-grafana-files:/etc/grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    depends_on:
      - prometheus

volumes:
  prometheusdata:
  shared-grafana-files:
  shared-prometheus-files: